module.exports = [
	{ az: 'af-south-1a', region: 'af-south-1', name: 'Africa (Cape Town)'},
	{ az: 'af-south-1b', region: 'af-south-1', name: 'Africa (Cape Town)'},
	{ az: 'af-south-1c', region: 'af-south-1', name: 'Africa (Cape Town)'},
	{ az: 'ap-east-1a', region: 'ap-east-1', name: 'Asia Pacific (Hong Kong)'},
	{ az: 'ap-east-1b', region: 'ap-east-1', name: 'Asia Pacific (Hong Kong)'},
	{ az: 'ap-east-1c', region: 'ap-east-1', name: 'Asia Pacific (Hong Kong)'},
	{ az: 'ap-northeast-1a', region: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)'},
	{ az: 'ap-northeast-1c', region: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)'},
	{ az: 'ap-northeast-1d', region: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)'},
	{ az: 'ap-northeast-2a', region: 'ap-northeast-2', name: 'Asia Pacific (Seoul)'},
	{ az: 'ap-northeast-2b', region: 'ap-northeast-2', name: 'Asia Pacific (Seoul)'},
	{ az: 'ap-northeast-2c', region: 'ap-northeast-2', name: 'Asia Pacific (Seoul)'},
	{ az: 'ap-northeast-3a', region: 'ap-northeast-3', name: 'Asia Pacific (Osaka-Local)'},
	{ az: 'ap-northeast-3b', region: 'ap-northeast-3', name: 'Asia Pacific (Osaka-Local)'},
	{ az: 'ap-northeast-3c', region: 'ap-northeast-3', name: 'Asia Pacific (Osaka-Local)'},
	{ az: 'ap-south-1a', region: 'ap-south-1', name: 'Asia Pacific (Mumbai)'},
	{ az: 'ap-south-1b', region: 'ap-south-1', name: 'Asia Pacific (Mumbai)'},
	{ az: 'ap-south-1c', region: 'ap-south-1', name: 'Asia Pacific (Mumbai)'},
	{ az: 'ap-southeast-1a', region: 'ap-southeast-1', name: 'Asia Pacific (Singapore)'},
	{ az: 'ap-southeast-1b', region: 'ap-southeast-1', name: 'Asia Pacific (Singapore)'},
	{ az: 'ap-southeast-1c', region: 'ap-southeast-1', name: 'Asia Pacific (Singapore)'},
	{ az: 'ap-southeast-2a', region: 'ap-southeast-2', name: 'Asia Pacific (Sydney)'},
	{ az: 'ap-southeast-2b', region: 'ap-southeast-2', name: 'Asia Pacific (Sydney)'},
	{ az: 'ap-southeast-2c', region: 'ap-southeast-2', name: 'Asia Pacific (Sydney)'},
	{ az: 'ca-central-1a', region: 'ca-central-1', name: 'Canada (Central)'},
	{ az: 'ca-central-1b', region: 'ca-central-1', name: 'Canada (Central)'},
	{ az: 'ca-central-1d', region: 'ca-central-1', name: 'Canada (Central)'},
	{ az: 'cn-north-1a',  region: 'cn-north-1',  name: 'China (Beijing)' },
	{ az: 'cn-north-1b',  region: 'cn-north-1',  name: 'China (Beijing)' },
	{ az: 'cn-northwest-1a', region: 'cn-northwest-1', name: 'China (Ningxia)'},
	{ az: 'cn-northwest-1b', region: 'cn-northwest-1', name: 'China (Ningxia)'},
	{ az: 'cn-northwest-1c', region: 'cn-northwest-1', name: 'China (Ningxia)'},
	{ az: 'eu-central-1a', region: 'eu-central-1', name: 'EU (Frankfurt)'},
	{ az: 'eu-central-1b', region: 'eu-central-1', name: 'EU (Frankfurt)'},
	{ az: 'eu-central-1c', region: 'eu-central-1', name: 'EU (Frankfurt)'},
	{ az: 'eu-north-1a',  region: 'eu-north-1',  name: 'EU (Stockholm)' },
	{ az: 'eu-north-1b',  region: 'eu-north-1',  name: 'EU (Stockholm)' },
	{ az: 'eu-north-1c',  region: 'eu-north-1',  name: 'EU (Stockholm)' },
	{ az: 'eu-south-1a',  region: 'eu-south-1',  name: 'EU (Milan)' },
	{ az: 'eu-south-1b',  region: 'eu-south-1',  name: 'EU (Milan)' },
	{ az: 'eu-south-1c',  region: 'eu-south-1',  name: 'EU (Milan)' },
	{ az: 'eu-west-1a',  region: 'eu-west-1',  name: 'EU (Ireland)' },
	{ az: 'eu-west-1b',  region: 'eu-west-1',  name: 'EU (Ireland)' },
	{ az: 'eu-west-1c',  region: 'eu-west-1',  name: 'EU (Ireland)' },
	{ az: 'eu-west-2a',  region: 'eu-west-2',  name: 'EU (London)' },
	{ az: 'eu-west-2b',  region: 'eu-west-2',  name: 'EU (London)' },
	{ az: 'eu-west-2c',  region: 'eu-west-2',  name: 'EU (London)' },
	{ az: 'eu-west-3a',  region: 'eu-west-3',  name: 'EU (Paris)' },
	{ az: 'eu-west-3b',  region: 'eu-west-3',  name: 'EU (Paris)' },
	{ az: 'eu-west-3c',  region: 'eu-west-3',  name: 'EU (Paris)' },
	{ az: 'me-south-1a', region: 'me-south-1', name: 'Middle East (Bahrain)'},
	{ az: 'me-south-1b', region: 'me-south-1', name: 'Middle East (Bahrain)'},
	{ az: 'me-south-1c', region: 'me-south-1', name: 'Middle East (Bahrain)'},
	{ az: 'sa-east-1a', region: 'sa-east-1', name: 'South America (Sao Paulo)'},
	{ az: 'sa-east-1b', region: 'sa-east-1', name: 'South America (Sao Paulo)'},
	{ az: 'sa-east-1c', region: 'sa-east-1', name: 'South America (Sao Paulo)'},
	{ az: 'us-east-1a', region: 'us-east-1', name: 'US East (N. Virginia)'},
	{ az: 'us-east-1b', region: 'us-east-1', name: 'US East (N. Virginia)'},
	{ az: 'us-east-1c', region: 'us-east-1', name: 'US East (N. Virginia)'},
	{ az: 'us-east-1d', region: 'us-east-1', name: 'US East (N. Virginia)'},
	{ az: 'us-east-1e', region: 'us-east-1', name: 'US East (N. Virginia)'},
	{ az: 'us-east-1f', region: 'us-east-1', name: 'US East (N. Virginia)'},
	{ az: 'us-east-2a',  region: 'us-east-2',  name: 'US East (Ohio)' },
	{ az: 'us-east-2b',  region: 'us-east-2',  name: 'US East (Ohio)' },
	{ az: 'us-east-2c',  region: 'us-east-2',  name: 'US East (Ohio)' },
	{ az: 'us-gov-east-1a', region: 'us-gov-east-1', name: 'AWS GovCloud (US-East)'},
	{ az: 'us-gov-east-1b', region: 'us-gov-east-1', name: 'AWS GovCloud (US-East)'},
	{ az: 'us-gov-east-1c', region: 'us-gov-east-1', name: 'AWS GovCloud (US-East)'},
	{ az: 'us-gov-west-1a', region: 'us-gov-west-1', name: 'AWS GovCloud (US-West)'},
	{ az: 'us-gov-west-1b', region: 'us-gov-west-1', name: 'AWS GovCloud (US-West)'},
	{ az: 'us-gov-west-1c', region: 'us-gov-west-1', name: 'AWS GovCloud (US-West)'},
	{ az: 'us-west-1a', region: 'us-west-1', name: 'US West (N. California)'},
	{ az: 'us-west-1b', region: 'us-west-1', name: 'US West (N. California)'},
	{ az: 'us-west-2a',  region: 'us-west-2',  name: 'US West (Oregon)' },
	{ az: 'us-west-2b',  region: 'us-west-2',  name: 'US West (Oregon)' },
	{ az: 'us-west-2c',  region: 'us-west-2',  name: 'US West (Oregon)' },
	{ az: 'us-west-2d',  region: 'us-west-2',  name: 'US West (Oregon)' }
]

