module.exports = [
	{ az: 'asia-east1-a', region: 'asia-east1', name: 'Changhua County, Taiwan, APAC' },
	{ az: 'asia-east1-b', region: 'asia-east1', name: 'Changhua County, Taiwan, APAC' },
	{ az: 'asia-east1-c', region: 'asia-east1', name: 'Changhua County, Taiwan, APAC' },
	{ az: 'asia-east2-a',  region: 'asia-east2',  name: 'Hong Kong, APAC' },
	{ az: 'asia-east2-b',  region: 'asia-east2',  name: 'Hong Kong, APAC' },
	{ az: 'asia-east2-c',  region: 'asia-east2',  name: 'Hong Kong, APAC' },
	{ az: 'asia-northeast1-a', region: 'asia-northeast1', name: 'Tokyo, Japan, APAC' },
	{ az: 'asia-northeast1-b', region: 'asia-northeast1', name: 'Tokyo, Japan, APAC' },
	{ az: 'asia-northeast1-c', region: 'asia-northeast1', name: 'Tokyo, Japan, APAC' },
	{ az: 'asia-northeast2-a', region: 'asia-northeast2', name: 'Osaka, Japan, APAC' },
	{ az: 'asia-northeast2-b', region: 'asia-northeast2', name: 'Osaka, Japan, APAC' },
	{ az: 'asia-northeast2-c', region: 'asia-northeast2', name: 'Osaka, Japan, APAC' },
	{ az: 'asia-northeast3-a', region: 'asia-northeast3', name: 'Seoul, South Korea, APAC' },
	{ az: 'asia-northeast3-b', region: 'asia-northeast3', name: 'Seoul, South Korea, APAC' },
	{ az: 'asia-northeast3-c', region: 'asia-northeast3', name: 'Seoul, South Korea, APAC' },
	{ az: 'asia-south1-a', region: 'asia-south1', name: 'Mumbai, India APAC' },
	{ az: 'asia-south1-b', region: 'asia-south1', name: 'Mumbai, India APAC' },
	{ az: 'asia-south1-c', region: 'asia-south1', name: 'Mumbai, India APAC' },
	{ az: 'asia-south2-a', region: 'asia-south2', name: 'Delhi, India APAC' },
	{ az: 'asia-south2-b', region: 'asia-south2', name: 'Delhi, India APAC' },
	{ az: 'asia-south2-c', region: 'asia-south2', name: 'Delhi, India APAC' },
	{ az: 'asia-southeast1-a', region: 'asia-southeast1', name: 'Jurong West, Singapore, APAC' },
	{ az: 'asia-southeast1-b', region: 'asia-southeast1', name: 'Jurong West, Singapore, APAC' },
	{ az: 'asia-southeast1-c', region: 'asia-southeast1', name: 'Jurong West, Singapore, APAC' },
	{ az: 'asia-southeast2-a', region: 'asia-southeast2', name: 'Jakarta, Indonesia, APAC' },
	{ az: 'asia-southeast2-b', region: 'asia-southeast2', name: 'Jakarta, Indonesia, APAC' },
	{ az: 'asia-southeast2-c', region: 'asia-southeast2', name: 'Jakarta, Indonesia, APAC' },
	{ az: 'australia-southeast1-a', region: 'australia-southeast1', name: 'Sydney, Australia, APAC' },
	{ az: 'australia-southeast1-b', region: 'australia-southeast1', name: 'Sydney, Australia, APAC' },
	{ az: 'australia-southeast1-c', region: 'australia-southeast1', name: 'Sydney, Australia, APAC' },
	{ az: 'australia-southeast2-a', region: 'australia-southeast2', name: 'Melbourne, Australia, APAC' },
	{ az: 'australia-southeast2-b', region: 'australia-southeast2', name: 'Melbourne, Australia, APAC' },
	{ az: 'australia-southeast2-c', region: 'australia-southeast2', name: 'Melbourne, Australia, APAC' },
	{ az: 'europe-central2-a', region: 'europe-central2', name: 'Warsaw, Poland, Europe' },
	{ az: 'europe-central2-b', region: 'europe-central2', name: 'Warsaw, Poland, Europe' },
	{ az: 'europe-central2-c', region: 'europe-central2', name: 'Warsaw, Poland, Europe' },
	{ az: 'europe-north1-a', region: 'europe-north1', name: 'Hamina, Finland, Europe' },
	{ az: 'europe-north1-b', region: 'europe-north1', name: 'Hamina, Finland, Europe' },
	{ az: 'europe-north1-c', region: 'europe-north1', name: 'Hamina, Finland, Europe' },
	{ az: 'europe-west1-b', region: 'europe-west1', name: 'St. Ghislain, Belgium, Europe' },
	{ az: 'europe-west1-c', region: 'europe-west1', name: 'St. Ghislain, Belgium, Europe' },
	{ az: 'europe-west1-d', region: 'europe-west1', name: 'St. Ghislain, Belgium, Europe' },
	{ az: 'europe-west2-a', region: 'europe-west2', name: 'London, England, Europe' },
	{ az: 'europe-west2-b', region: 'europe-west2', name: 'London, England, Europe' },
	{ az: 'europe-west2-c', region: 'europe-west2', name: 'London, England, Europe' },
	{ az: 'europe-west3-a', region: 'europe-west3', name: 'Frankfurt, Germany Europe' },
	{ az: 'europe-west3-b', region: 'europe-west3', name: 'Frankfurt, Germany Europe' },
	{ az: 'europe-west3-c', region: 'europe-west3', name: 'Frankfurt, Germany Europe' },
	{ az: 'europe-west4-a', region: 'europe-west4', name: 'Eemshaven, Netherlands, Europe' },
	{ az: 'europe-west4-b', region: 'europe-west4', name: 'Eemshaven, Netherlands, Europe' },
	{ az: 'europe-west4-c', region: 'europe-west4', name: 'Eemshaven, Netherlands, Europe' },
	{ az: 'europe-west6-a', region: 'europe-west6', name: 'Zurich, Switzerland, Europe' },
	{ az: 'europe-west6-b', region: 'europe-west6', name: 'Zurich, Switzerland, Europe' },
	{ az: 'europe-west6-c', region: 'europe-west6', name: 'Zurich, Switzerland, Europe' },
	{ az: 'northamerica-northeast1-a', region: 'northamerica-northeast1', name: 'Montréal, Québec, North America' },
	{ az: 'northamerica-northeast1-b', region: 'northamerica-northeast1', name: 'Montréal, Québec, North America' },
	{ az: 'northamerica-northeast1-c', region: 'northamerica-northeast1', name: 'Montréal, Québec, North America' },
	{ az: 'southamerica-east1-a', region: 'southamerica-east1', name: 'Osasco, São Paulo, Brazil, South America' },
	{ az: 'southamerica-east1-b', region: 'southamerica-east1', name: 'Osasco, São Paulo, Brazil, South America' },
	{ az: 'southamerica-east1-c', region: 'southamerica-east1', name: 'Osasco, São Paulo, Brazil, South America' },
	{ az: 'us-central1-a', region: 'us-central1', name: 'Council Bluffs, Iowa, North America' },
	{ az: 'us-central1-b', region: 'us-central1', name: 'Council Bluffs, Iowa, North America' },
	{ az: 'us-central1-c', region: 'us-central1', name: 'Council Bluffs, Iowa, North America' },
	{ az: 'us-central1-f', region: 'us-central1', name: 'Council Bluffs, Iowa, North America' },
	{ az: 'us-east1-b', region: 'us-east1', name: 'Moncks Corner, South Carolina, North America' },
	{ az: 'us-east1-c', region: 'us-east1', name: 'Moncks Corner, South Carolina, North America' },
	{ az: 'us-east1-d', region: 'us-east1', name: 'Moncks Corner, South Carolina, North America' },
	{ az: 'us-east4-a', region: 'us-east4', name: 'Ashburn, Virginia, North America' },
	{ az: 'us-east4-b', region: 'us-east4', name: 'Ashburn, Virginia, North America' },
	{ az: 'us-east4-c', region: 'us-east4', name: 'Ashburn, Virginia, North America' },
	{ az: 'us-west1-a', region: 'us-west1', name: 'The Dalles, Oregon, North America' },
	{ az: 'us-west1-b', region: 'us-west1', name: 'The Dalles, Oregon, North America' },
	{ az: 'us-west1-c', region: 'us-west1', name: 'The Dalles, Oregon, North America' },
	{ az: 'us-west2-a', region: 'us-west2', name: 'Los Angeles, California, North America' },
	{ az: 'us-west2-b', region: 'us-west2', name: 'Los Angeles, California, North America' },
	{ az: 'us-west2-c', region: 'us-west2', name: 'Los Angeles, California, North America' },
	{ az: 'us-west3-a', region: 'us-west3', name: 'Salt Lake City, Utah, North America' },
	{ az: 'us-west3-b', region: 'us-west3', name: 'Salt Lake City, Utah, North America' },
	{ az: 'us-west3-c', region: 'us-west3', name: 'Salt Lake City, Utah, North America' },
	{ az: 'us-west4-a', region: 'us-west4', name: 'Las Vegas, Nevada, North America' },
	{ az: 'us-west4-b', region: 'us-west4', name: 'Las Vegas, Nevada, North America' },
	{ az: 'us-west4-c', region: 'us-west4', name: 'Las Vegas, Nevada, North America' }
]

