module.exports = [
	{ code: 'asia-east1-a', name: 'Changhua County, Taiwan, APAC' },
	{ code: 'asia-east1-b', name: 'Changhua County, Taiwan, APAC' },
	{ code: 'asia-east1-c', name: 'Changhua County, Taiwan, APAC' },
	{ code: 'asia-east2-a', name: 'Hong Kong, APAC' },
	{ code: 'asia-east2-b', name: 'Hong Kong, APAC' },
	{ code: 'asia-east2-c', name: 'Hong Kong, APAC' },
	{ code: 'asia-northeast1-a', name: 'Tokyo, Japan, APAC' },
	{ code: 'asia-northeast1-b', name: 'Tokyo, Japan, APAC' },
	{ code: 'asia-northeast1-c', name: 'Tokyo, Japan, APAC' },
	{ code: 'asia-northeast2-a', name: 'Osaka, Japan, APAC' },
	{ code: 'asia-northeast2-b', name: 'Osaka, Japan, APAC' },
	{ code: 'asia-northeast2-c', name: 'Osaka, Japan, APAC' },
	{ code: 'asia-northeast3-a', name: 'Seoul, South Korea, APAC' },
	{ code: 'asia-northeast3-b', name: 'Seoul, South Korea, APAC' },
	{ code: 'asia-northeast3-c', name: 'Seoul, South Korea, APAC' },
	{ code: 'asia-south1-a', name: 'Mumbai, India APAC' },
	{ code: 'asia-south1-b', name: 'Mumbai, India APAC' },
	{ code: 'asia-south1-c', name: 'Mumbai, India APAC' },
	{ code: 'asia-south2-a', name: 'Delhi, India APAC' },
	{ code: 'asia-south2-b', name: 'Delhi, India APAC' },
	{ code: 'asia-south2-c', name: 'Delhi, India APAC' },
	{ code: 'asia-southeast1-a', name: 'Jurong West, Singapore, APAC' },
	{ code: 'asia-southeast1-b', name: 'Jurong West, Singapore, APAC' },
	{ code: 'asia-southeast1-c', name: 'Jurong West, Singapore, APAC' },
	{ code: 'asia-southeast2-a', name: 'Jakarta, Indonesia, APAC' },
	{ code: 'asia-southeast2-b', name: 'Jakarta, Indonesia, APAC' },
	{ code: 'asia-southeast2-c', name: 'Jakarta, Indonesia, APAC' },
	{ code: 'australia-southeast1-a', name: 'Sydney, Australia, APAC' },
	{ code: 'australia-southeast1-b', name: 'Sydney, Australia, APAC' },
	{ code: 'australia-southeast1-c', name: 'Sydney, Australia, APAC' },
	{ code: 'australia-southeast2-a', name: 'Melbourne, Australia, APAC' },
	{ code: 'australia-southeast2-b', name: 'Melbourne, Australia, APAC' },
	{ code: 'australia-southeast2-c', name: 'Melbourne, Australia, APAC' },
	{ code: 'europe-central2-a', name: 'Warsaw, Poland, Europe' },
	{ code: 'europe-central2-b', name: 'Warsaw, Poland, Europe' },
	{ code: 'europe-central2-c', name: 'Warsaw, Poland, Europe' },
	{ code: 'europe-north1-a', name: 'Hamina, Finland, Europe' },
	{ code: 'europe-north1-b', name: 'Hamina, Finland, Europe' },
	{ code: 'europe-north1-c', name: 'Hamina, Finland, Europe' },
	{ code: 'europe-west1-b', name: 'St. Ghislain, Belgium, Europe' },
	{ code: 'europe-west1-c', name: 'St. Ghislain, Belgium, Europe' },
	{ code: 'europe-west1-d', name: 'St. Ghislain, Belgium, Europe' },
	{ code: 'europe-west2-a', name: 'London, England, Europe' },
	{ code: 'europe-west2-b', name: 'London, England, Europe' },
	{ code: 'europe-west2-c', name: 'London, England, Europe' },
	{ code: 'europe-west3-a', name: 'Frankfurt, Germany Europe' },
	{ code: 'europe-west3-b', name: 'Frankfurt, Germany Europe' },
	{ code: 'europe-west3-c', name: 'Frankfurt, Germany Europe' },
	{ code: 'europe-west4-a', name: 'Eemshaven, Netherlands, Europe' },
	{ code: 'europe-west4-b', name: 'Eemshaven, Netherlands, Europe' },
	{ code: 'europe-west4-c', name: 'Eemshaven, Netherlands, Europe' },
	{ code: 'europe-west6-a', name: 'Zurich, Switzerland, Europe' },
	{ code: 'europe-west6-b', name: 'Zurich, Switzerland, Europe' },
	{ code: 'europe-west6-c', name: 'Zurich, Switzerland, Europe' },
	{ code: 'northamerica-northeast1-a', name: 'Montréal, Québec, North America' },
	{ code: 'northamerica-northeast1-b', name: 'Montréal, Québec, North America' },
	{ code: 'northamerica-northeast1-c', name: 'Montréal, Québec, North America' },
	{ code: 'southamerica-east1-a', name: 'Osasco, São Paulo, Brazil, South America' },
	{ code: 'southamerica-east1-b', name: 'Osasco, São Paulo, Brazil, South America' },
	{ code: 'southamerica-east1-c', name: 'Osasco, São Paulo, Brazil, South America' },
	{ code: 'us-central1-a', name: 'Council Bluffs, Iowa, North America' },
	{ code: 'us-central1-b', name: 'Council Bluffs, Iowa, North America' },
	{ code: 'us-central1-c', name: 'Council Bluffs, Iowa, North America' },
	{ code: 'us-central1-f', name: 'Council Bluffs, Iowa, North America' },
	{ code: 'us-east1-b', name: 'Moncks Corner, South Carolina, North America' },
	{ code: 'us-east1-c', name: 'Moncks Corner, South Carolina, North America' },
	{ code: 'us-east1-d', name: 'Moncks Corner, South Carolina, North America' },
	{ code: 'us-east4-a', name: 'Ashburn, Virginia, North America' },
	{ code: 'us-east4-b', name: 'Ashburn, Virginia, North America' },
	{ code: 'us-east4-c', name: 'Ashburn, Virginia, North America' },
	{ code: 'us-west1-a', name: 'The Dalles, Oregon, North America' },
	{ code: 'us-west1-b', name: 'The Dalles, Oregon, North America' },
	{ code: 'us-west1-c', name: 'The Dalles, Oregon, North America' },
	{ code: 'us-west2-a', name: 'Los Angeles, California, North America' },
	{ code: 'us-west2-b', name: 'Los Angeles, California, North America' },
	{ code: 'us-west2-c', name: 'Los Angeles, California, North America' },
	{ code: 'us-west3-a', name: 'Salt Lake City, Utah, North America' },
	{ code: 'us-west3-b', name: 'Salt Lake City, Utah, North America' },
	{ code: 'us-west3-c', name: 'Salt Lake City, Utah, North America' },
	{ code: 'us-west4-a', name: 'Las Vegas, Nevada, North America' },
	{ code: 'us-west4-b', name: 'Las Vegas, Nevada, North America' },
	{ code: 'us-west4-c', name: 'Las Vegas, Nevada, North America' }
]

